#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034

START=90
STOP=10
USE_PROCD=1

start_service() {
	[ -s /etc/gofro/relay-endpoint ] || return 0
	sysctl -w net.core.rmem_max=4194304 >/dev/null
	sysctl -w net.core.wmem_max=4194304 >/dev/null

	procd_open_instance
	procd_set_param command /usr/bin/gofro-relay client
	procd_append_param command --server-file /etc/gofro/relay-endpoint
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
