#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034

START=96
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/libexec/gofro/update
	procd_set_param respawn
	procd_close_instance
}
