export type {
  Device,
  AuthStatus,
  DomainRule,
  HistoryPoint,
  IpRule,
  ProfileInput,
  Profile,
  RouteTarget,
  RoutingConfig,
  RoutingTest,
  Server,
  ServerProbe,
  ServerInput,
  ServerVersion,
  Status,
  WifiBand,
  WifiInput,
  OnboardingStatus,
  OnboardingWifiInput,
} from "../api/schemas";
